/**
 * After a client submits the onboarding questionnaire, generate DRAFT
 * training program and nutrition plan from their answers.
 *
 * "Draft" is implicit: rows are created in training_programs / nutrition_plans,
 * but the client's UI still hides them via AccessGate until the trainer flips
 * client_access.status to 'active'. The trainer sees the drafts on the client
 * detail page and can edit before opening access.
 *
 * Called from client-side (browser session) — RLS "Owner inserts own program"
 * allows the client to create their own program row.
 */
import { supabase } from "@/integrations/supabase/client";
import {
  loadExercises,
  createOrReplaceProgram,
} from "@/lib/training-repo";
import {
  loadDishes,
  loadTargetProfile,
  createOrReplacePlan,
  extractExcludedFromText,
} from "@/lib/nutrition-repo";
import {
  inferGoal,
  inferLevel,
  type ProgramInput,
} from "@/lib/training";
import { calcTargets } from "@/lib/nutrition";

async function loadLatestWeightKg(userId: string): Promise<number | null> {
  const { data } = await supabase
    .from("measurements")
    .select("weight_kg")
    .eq("user_id", userId)
    .not("weight_kg", "is", null)
    .order("measured_on", { ascending: false })
    .limit(1)
    .maybeSingle();
  const w = data?.weight_kg;
  return typeof w === "number" && Number.isFinite(w) ? w : w != null ? Number(w) : null;
}

type OnboardingRow = {
  goal_primary: string | null;
  training_days_per_week: number | null;
  training_location: string | null;
  equipment: string[] | null;
  has_injuries: boolean | null;
  injuries_details: string | null;
  activity_level: string | null;
  meals_per_day: number | null;
  favorite_foods: string | null;
  disliked_foods: string | null;
  allergies: string | null;
};

/**
 * Generate/refresh training and nutrition drafts for a client based on
 * their onboarding answers. Skips silently if the program/plan already
 * exists and was manually edited (targets_manual flag).
 */
export async function autoGenerateDraftsForClient(userId: string): Promise<{
  training: boolean;
  nutrition: boolean;
  errors: string[];
}> {
  const errors: string[] = [];
  let training = false;
  let nutrition = false;

  // Load onboarding answers
  const { data: onb, error: onbErr } = await supabase
    .from("onboarding_responses")
    .select(
      "goal_primary, training_days_per_week, training_location, equipment, has_injuries, injuries_details, activity_level, meals_per_day, favorite_foods, disliked_foods, allergies",
    )
    .eq("user_id", userId)
    .maybeSingle();

  if (onbErr || !onb) {
    errors.push("Не удалось прочитать анкету");
    return { training, nutrition, errors };
  }
  const o = onb as OnboardingRow;

  // ---------- Training draft ----------
  try {
    const { data: existing } = await supabase
      .from("training_programs")
      .select("id, targets_manual")
      .eq("user_id", userId)
      .maybeSingle();

    if (existing?.targets_manual) {
      // Trainer already customized — do not overwrite.
    } else {
      const weight_kg = await loadLatestWeightKg(userId);
      const days = clampDays(o.training_days_per_week);
      const input: ProgramInput = {
        sessions_per_week: days,
        goal: inferGoal(o.goal_primary),
        level: inferLevel(o.activity_level),
        has_injuries: Boolean(o.has_injuries),
        injuries_details: o.injuries_details,
        equipment: o.equipment ?? [],
        location: o.training_location,
        weight_kg,
      };
      const exercises = await loadExercises();
      if (exercises.length > 0) {
        await createOrReplaceProgram({
          userId,
          input,
          exercises,
          preserveNotes: null,
          preserveFaq: null,
          targetsManual: false,
        });
        training = true;
      } else {
        errors.push("В базе нет упражнений — тренировочный черновик не создан");
      }
    }
  } catch (e) {
    errors.push(`Тренировки: ${(e as Error).message}`);
  }

  // ---------- Nutrition draft ----------
  try {
    const { data: existingPlan } = await supabase
      .from("nutrition_plans")
      .select("id, targets_manual")
      .eq("user_id", userId)
      .maybeSingle();

    if (existingPlan?.targets_manual) {
      // Trainer already customized — do not overwrite.
    } else {
      const profile = await loadTargetProfile(userId);
      const targets = calcTargets(profile);
      const mealsPerDay: 3 | 5 = o.meals_per_day && o.meals_per_day >= 4 ? 5 : 3;
      const excluded = extractExcludedFromText(o.allergies, o.disliked_foods);
      const preferred = (o.favorite_foods ?? "")
        .split(/[,\n]/)
        .map((s) => s.trim().toLowerCase())
        .filter(Boolean)
        .slice(0, 20);

      const dishes = await loadDishes();
      if (dishes.length > 0) {
        await createOrReplacePlan({
          userId,
          mealsPerDay,
          preferred,
          excluded,
          targets,
          targetsManual: false,
          dishes,
        });
        nutrition = true;
      } else {
        errors.push("В базе нет блюд — план питания не создан");
      }
    }
  } catch (e) {
    errors.push(`Питание: ${(e as Error).message}`);
  }

  return { training, nutrition, errors };
}

function clampDays(n: number | null): 3 | 4 {
  if (!n) return 3;
  return n >= 4 ? 4 : 3;
}
