/**
 * After a client submits the onboarding questionnaire, generate DRAFT
 * training program and nutrition plan from their answers.
 *
 * Персонализация: профиль клиента + safety gate + валидация (см. src/lib/personalization).
 * LLM не считает калории/БЖУ — только calcTargets() и generatePlan().
 */
import { supabase } from "@/integrations/supabase/client";
import {
  loadExercises,
  createOrReplaceProgram,
  createOrReplaceCustomProgram,
} from "@/lib/training-repo";
import {
  loadDishes,
  loadTargetProfile,
  createOrReplacePlan,
  extractExcludedFromText,
} from "@/lib/nutrition-repo";
import {
  inferGoal,
  inferLevel,
  type ProgramInput,
} from "@/lib/training";
import {
  canBuildCoachSheetProgram,
  coachSheetExercisePool,
  missingCoachSheetExercises,
  resolveDefaultTrainingProgram,
} from "@/lib/coach-sheet-program";
import { calcTargets } from "@/lib/nutrition";
import { normalizeFoodTerms } from "@/lib/food-products";
import {
  buildClientProfile,
  explainProgramForClient,
  validateTrainingProgram,
  validateMacroConsistency,
  type GeneratedProgramMeta,
} from "@/lib/personalization";

async function loadLatestWeightKg(userId: string): Promise<number | null> {
  const { data } = await supabase
    .from("measurements")
    .select("weight_kg")
    .eq("user_id", userId)
    .not("weight_kg", "is", null)
    .order("measured_on", { ascending: false })
    .limit(1)
    .maybeSingle();
  const w = data?.weight_kg;
  return typeof w === "number" && Number.isFinite(w) ? w : w != null ? Number(w) : null;
}

async function loadDemographics(userId: string) {
  const [profileRes, weight_kg] = await Promise.all([
    supabase
      .from("profiles")
      .select("gender, birth_date, height_cm")
      .eq("id", userId)
      .maybeSingle(),
    loadLatestWeightKg(userId),
  ]);
  return {
    gender: (profileRes.data?.gender as "female" | "male" | null) ?? null,
    birth_date: profileRes.data?.birth_date ?? null,
    height_cm: profileRes.data?.height_cm ?? null,
    weight_kg,
  };
}

type OnboardingRow = Record<string, unknown> & { user_id: string };

async function persistGenerationMeta(
  userId: string,
  meta: GeneratedProgramMeta,
): Promise<void> {
  const { data } = await supabase
    .from("onboarding_responses")
    .select("extra")
    .eq("user_id", userId)
    .maybeSingle();

  const prev = (data?.extra && typeof data.extra === "object" ? data.extra : {}) as Record<
    string,
    unknown
  >;

  await supabase
    .from("onboarding_responses")
    .update({
      extra: {
        ...prev,
        generation_meta: meta,
      } as never,
    })
    .eq("user_id", userId);
}

/**
 * Generate training and nutrition drafts once per client based on
 * onboarding answers. Never overwrites an existing program/plan —
 * only the trainer may edit afterwards.
 */
export async function autoGenerateDraftsForClient(userId: string): Promise<{
  training: boolean;
  nutrition: boolean;
  requires_trainer_review: boolean;
  errors: string[];
}> {
  const errors: string[] = [];
  let training = false;
  let nutrition = false;

  const { data: onb, error: onbErr } = await supabase
    .from("onboarding_responses")
    .select("*")
    .eq("user_id", userId)
    .maybeSingle();

  if (onbErr || !onb) {
    errors.push("Не удалось прочитать анкету");
    return { training, nutrition, requires_trainer_review: false, errors };
  }

  const o = onb as OnboardingRow;
  const demographics = await loadDemographics(userId);
  const clientProfile = buildClientProfile(
    {
      user_id: userId,
      goal_primary: o.goal_primary as string | null,
      goal_details: o.goal_details as string | null,
      timeframe: o.timeframe as string | null,
      experience: o.experience as string | null,
      activity_level: o.activity_level as string | null,
      training_days_per_week: o.training_days_per_week as number | null,
      session_duration_min: o.session_duration_min as number | null,
      training_location: o.training_location as string | null,
      equipment: (o.equipment as string[]) ?? [],
      focus_areas: (o.focus_areas as string[]) ?? [],
      has_injuries: o.has_injuries as boolean | null,
      injuries_details: o.injuries_details as string | null,
      health_conditions: o.health_conditions as string | null,
      medications: o.medications as string | null,
      pregnancy_status: o.pregnancy_status as string | null,
      meals_per_day: o.meals_per_day as number | null,
      favorite_foods: o.favorite_foods as string | null,
      disliked_foods: o.disliked_foods as string | null,
      allergies: o.allergies as string | null,
      diet_type: o.diet_type as string | null,
      sleep_hours: o.sleep_hours as number | null,
      stress_level: o.stress_level as number | null,
      energy_level: o.energy_level as number | null,
      job_type: o.job_type as string | null,
      extra: (o.extra as Record<string, unknown>) ?? null,
    },
    demographics,
  );

  const requires_trainer_review = clientProfile.safety.requires_trainer_review;
  const trainerNote = clientProfile.safety.trainer_note;
  const clientExplanation = explainProgramForClient(clientProfile);

  const metaBase: GeneratedProgramMeta = {
    program_version: "1.0.0",
    generated_at: new Date().toISOString(),
    client_profile_snapshot: clientProfile,
    safety_flags: clientProfile.safety.flags,
    requires_trainer_review,
    requires_medical_clearance: clientProfile.safety.requires_medical_clearance,
    validation: { ok: true, issues: [] },
    reason_for_changes: null,
  };

  // ---------- Training draft ----------
  try {
    const { data: existing } = await supabase
      .from("training_programs")
      .select("id, targets_manual")
      .eq("user_id", userId)
      .maybeSingle();

    if (existing) {
      // Программа уже есть — не трогаем (фиксированный блок; правит только тренер).
    } else {
      const days = clampDays(o.training_days_per_week as number | null);
      const input: ProgramInput = {
        sessions_per_week: days,
        goal: inferGoal(o.goal_primary as string | null),
        level: inferLevel(o.activity_level as string | null),
        has_injuries: Boolean(o.has_injuries),
        injuries_details: o.injuries_details as string | null,
        equipment: (o.equipment as string[]) ?? [],
        location: o.training_location as string | null,
        weight_kg: demographics.weight_kg,
      };
      const exercises = await loadExercises();
      if (exercises.length > 0) {
        const plan = resolveDefaultTrainingProgram(exercises, input);
        const validation = validateTrainingProgram({
          days: plan.days,
          exercises,
          profile: clientProfile,
        });

        metaBase.validation = validation;

        if (!canBuildCoachSheetProgram(exercises) && coachSheetExercisePool(exercises).length < 4) {
          const missing = missingCoachSheetExercises(exercises);
          errors.push(
            `В базе нет упражнений из таблицы тренера (${missing.slice(0, 3).join(", ")}${missing.length > 3 ? "…" : ""}). Выполните SQL seed в Supabase.`,
          );
        }

        if (!validation.ok) {
          errors.push(
            ...validation.issues
              .filter((i) => i.severity === "error")
              .map((i) => `Тренировки: ${i.message}`),
          );
        } else if (plan.mode === "coach_sheet") {
          const notesParts = [clientExplanation, plan.coachNotes];
          if (trainerNote) notesParts.unshift(trainerNote);

          await createOrReplaceCustomProgram({
            userId,
            input: { ...input, sessions_per_week: 3 },
            days: plan.days,
            programWeeks: plan.programWeeks,
            notes: notesParts.filter(Boolean).join("\n\n"),
            preserveFaq: null,
            // Фиксируем сразу: дальше правит только тренер.
            targetsManual: true,
          });
          training = true;
        } else {
          const notesParts = [clientExplanation, plan.coachNotes].filter(Boolean);
          if (trainerNote) notesParts.unshift(trainerNote);

          await createOrReplaceProgram({
            userId,
            input,
            exercises,
            preserveNotes: notesParts.join("\n\n"),
            preserveFaq: null,
            targetsManual: true,
            preGeneratedDays: plan.days,
          });
          training = true;
        }
      } else {
        errors.push("В базе нет упражнений — тренировочный черновик не создан");
      }
    }
  } catch (e) {
    errors.push(`Тренировки: ${(e as Error).message}`);
  }

  // ---------- Nutrition draft ----------
  try {
    const { data: existingPlan } = await supabase
      .from("nutrition_plans")
      .select("id, targets_manual")
      .eq("user_id", userId)
      .maybeSingle();

    if (existingPlan) {
      // План уже есть — не трогаем (фиксированный блок; правит только тренер).
    } else {
      const profile = await loadTargetProfile(userId);
      const targets = calcTargets(profile);
      const macroCheck = validateMacroConsistency(targets);
      if (!macroCheck.ok) {
        errors.push("Питание: расхождение калорий и макросов");
      }

      const mealsPerDay: 3 | 5 =
        o.meals_per_day && (o.meals_per_day as number) >= 4 ? 5 : 3;
      const excluded = extractExcludedFromText(
        o.allergies as string | null,
        o.disliked_foods as string | null,
      );
      const preferred = normalizeFoodTerms(
        ((o.favorite_foods as string) ?? "")
          .split(/[,;\n]+/)
          .map((s) => s.trim().toLowerCase())
          .filter(Boolean)
          .slice(0, 30),
      );

      const dishes = await loadDishes();
      if (dishes.length > 0 && macroCheck.ok) {
        await createOrReplacePlan({
          userId,
          mealsPerDay,
          preferred,
          excluded,
          targets,
          // Фиксируем сразу: клиент может только перетасовать блюда плана.
          targetsManual: true,
          dishes,
        });
        nutrition = true;
      } else if (dishes.length === 0) {
        errors.push("В базе нет блюд — план питания не создан");
      }
    }
  } catch (e) {
    errors.push(`Питание: ${(e as Error).message}`);
  }

  try {
    await persistGenerationMeta(userId, metaBase);
  } catch {
    errors.push("Не удалось сохранить метаданные генерации");
  }

  return { training, nutrition, requires_trainer_review, errors };
}

function clampDays(n: number | null): 3 | 4 {
  if (!n) return 3;
  return n >= 4 ? 4 : 3;
}
