/**
 * Белый список продуктов конструктора рационов.
 * KBJU verified — USDA FoodData Central (SR Legacy / Foundation).
 * is_verified=false — требуется этикетка конкретной упаковки.
 */
export type SeedProduct = {
  slug: string;
  name: string;
  category: string;
  brand?: string | null;
  state: string;
  measurement_basis: string;
  kcal: number;
  protein: number;
  fat: number;
  carbs: number;
  fiber?: number | null;
  density?: number | null;
  source_name: string;
  source_url?: string | null;
  is_verified: boolean;
  allowed_for_snack: boolean;
  requires_cooking: boolean;
  weighing_note: string;
};

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    slug: "buckwheat-dry",
    name: "Гречка",
    category: "grain",
    state: "raw_dry",
    measurement_basis: "per_100g_dry",
    kcal: 343,
    protein: 13.25,
    fat: 3.4,
    carbs: 71.5,
    fiber: 10,
    source_name: "USDA FDC 20008",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Взвешивать сухой крупой.",
  },
  {
    slug: "rice-white-dry",
    name: "Рис",
    category: "grain",
    state: "raw_dry",
    measurement_basis: "per_100g_dry",
    kcal: 365,
    protein: 7.13,
    fat: 0.66,
    carbs: 79.95,
    fiber: 1.3,
    source_name: "USDA FDC 20047",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Взвешивать сухой крупой.",
  },
  {
    slug: "oats-dry",
    name: "Овсянка",
    category: "grain",
    state: "raw_dry",
    measurement_basis: "per_100g_dry",
    kcal: 389,
    protein: 16.89,
    fat: 6.9,
    carbs: 66.27,
    fiber: 10.6,
    source_name: "USDA FDC 20038",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Взвешивать сухими хлопьями.",
  },
  {
    slug: "cucumber",
    name: "Огурцы",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 15,
    protein: 0.65,
    fat: 0.11,
    carbs: 3.63,
    fiber: 0.5,
    source_name: "USDA FDC 168409",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Съедобная часть, сырая.",
  },
  {
    slug: "tomato",
    name: "Помидоры",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 18,
    protein: 0.88,
    fat: 0.2,
    carbs: 3.89,
    fiber: 1.2,
    source_name: "USDA FDC 170457",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Съедобная часть, сырые.",
  },
  {
    slug: "bell-pepper",
    name: "Перец",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 31,
    protein: 0.99,
    fat: 0.3,
    carbs: 6.03,
    fiber: 2.1,
    source_name: "USDA FDC 170427",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Съедобная часть без семян.",
  },
  {
    slug: "napa-cabbage",
    name: "Пекинская капуста",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 16,
    protein: 1.2,
    fat: 0.2,
    carbs: 3.23,
    fiber: 1.2,
    source_name: "USDA FDC 169975",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Съедобная часть, сырая.",
  },
  {
    slug: "white-cabbage",
    name: "Белокочанная капуста",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 25,
    protein: 1.28,
    fat: 0.1,
    carbs: 5.8,
    fiber: 2.5,
    source_name: "USDA FDC 169975",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Съедобная часть, сырая.",
  },
  {
    slug: "zucchini",
    name: "Кабачки",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 17,
    protein: 1.21,
    fat: 0.32,
    carbs: 3.11,
    fiber: 1,
    source_name: "USDA FDC 168565",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Съедобная часть, сырой.",
  },
  {
    slug: "eggplant",
    name: "Баклажаны",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 25,
    protein: 0.98,
    fat: 0.18,
    carbs: 5.88,
    fiber: 3,
    source_name: "USDA FDC 169246",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Съедобная часть, сырой.",
  },
  {
    slug: "carrot",
    name: "Морковь",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 41,
    protein: 0.93,
    fat: 0.24,
    carbs: 9.58,
    fiber: 2.8,
    source_name: "USDA FDC 170393",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Съедобная часть, сырая.",
  },
  {
    slug: "avocado",
    name: "Авокадо",
    category: "vegetable",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 160,
    protein: 2,
    fat: 14.66,
    carbs: 8.53,
    fiber: 6.7,
    source_name: "USDA FDC 171705",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Мякоть без косточки.",
  },
  {
    slug: "apple",
    name: "Яблоко",
    category: "fruit",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 52,
    protein: 0.26,
    fat: 0.17,
    carbs: 13.81,
    fiber: 2.4,
    source_name: "USDA FDC 171688",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Съедобная часть без сердцевины.",
  },
  {
    slug: "banana",
    name: "Банан",
    category: "fruit",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 89,
    protein: 1.09,
    fat: 0.33,
    carbs: 22.84,
    fiber: 2.6,
    source_name: "USDA FDC 173944",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Мякоть без кожуры.",
  },
  {
    slug: "cherry",
    name: "Вишня",
    category: "fruit",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 50,
    protein: 1,
    fat: 0.3,
    carbs: 12.18,
    fiber: 1.6,
    source_name: "USDA FDC 171719",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Без косточек.",
  },
  {
    slug: "lemon",
    name: "Лимон",
    category: "fruit",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 29,
    protein: 1.1,
    fat: 0.3,
    carbs: 9.32,
    fiber: 2.8,
    source_name: "USDA FDC 167746",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Съедобная часть.",
  },
  {
    slug: "chicken-breast-raw",
    name: "Курица",
    category: "meat",
    state: "raw",
    measurement_basis: "per_100g_raw",
    kcal: 120,
    protein: 22.5,
    fat: 2.62,
    carbs: 0,
    fiber: 0,
    source_name: "USDA FDC 171477",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Филе, сырое, до приготовления.",
  },
  {
    slug: "beef-lean-raw",
    name: "Говядина",
    category: "meat",
    state: "raw",
    measurement_basis: "per_100g_raw",
    kcal: 250,
    protein: 26,
    fat: 15,
    carbs: 0,
    fiber: 0,
    source_name: "USDA FDC 174032",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Постная часть, сырая, до приготовления.",
  },
  {
    slug: "pollock-raw",
    name: "Минтай",
    category: "fish",
    state: "raw",
    measurement_basis: "per_100g_raw",
    kcal: 72,
    protein: 15.9,
    fat: 0.9,
    carbs: 0,
    fiber: 0,
    source_name: "USDA FDC 175130",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Филе, сырое, до приготовления.",
  },
  {
    slug: "egg-whole",
    name: "Яйца",
    category: "dairy",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 143,
    protein: 12.56,
    fat: 9.51,
    carbs: 0.72,
    fiber: 0,
    source_name: "USDA FDC 171287",
    is_verified: true,
    allowed_for_snack: false,
    requires_cooking: true,
    weighing_note: "Съедобная часть (~50 г на 1 яйцо С1).",
  },
  {
    slug: "walnut",
    name: "Грецкий орех",
    category: "nut_seed",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 654,
    protein: 15.23,
    fat: 65.21,
    carbs: 13.71,
    fiber: 6.7,
    source_name: "USDA FDC 170187",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Очищенные ядра.",
  },
  {
    slug: "almond",
    name: "Миндаль",
    category: "nut_seed",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 579,
    protein: 21.15,
    fat: 49.93,
    carbs: 21.55,
    fiber: 12.5,
    source_name: "USDA FDC 170567",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Очищенные ядра.",
  },
  {
    slug: "pumpkin-seeds",
    name: "Семечки тыквы",
    category: "nut_seed",
    state: "raw",
    measurement_basis: "per_100g_edible",
    kcal: 559,
    protein: 30.23,
    fat: 49.05,
    carbs: 10.71,
    fiber: 6,
    source_name: "USDA FDC 170556",
    is_verified: true,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Очищенные семечки.",
  },
  // Непроверенные — только ручной ввод тренером или после этикетки
  {
    slug: "stevia-candy",
    name: "Конфеты со стевией",
    category: "sweet",
    brand: "уточнить",
    state: "ready",
    measurement_basis: "per_100g_pack",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "По этикетке упаковки.",
  },
  {
    slug: "marshmallow",
    name: "Зефир",
    category: "sweet",
    brand: "уточнить",
    state: "ready",
    measurement_basis: "per_100g_pack",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "По этикетке упаковки.",
  },
  {
    slug: "dried-mango",
    name: "Манго сушёное",
    category: "sweet",
    brand: "уточнить",
    state: "ready",
    measurement_basis: "per_100g_pack",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "По этикетке упаковки.",
  },
  {
    slug: "hard-cheese",
    name: "Сыр твёрдый",
    category: "dairy",
    brand: "уточнить",
    state: "ready",
    measurement_basis: "per_100g_pack",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "По этикетке упаковки.",
  },
  {
    slug: "lactose-free-milk",
    name: "Молоко без лактозы",
    category: "dairy",
    brand: "уточнить",
    state: "liquid",
    measurement_basis: "per_100g",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    density: 1.03,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "В граммах или мл по плотности на этикетке.",
  },
  {
    slug: "canned-tuna",
    name: "Тунец",
    category: "canned",
    brand: "уточнить",
    state: "canned_drained",
    measurement_basis: "per_100g_drained",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: false,
    requires_cooking: false,
    weighing_note: "Без жидкости из банки.",
  },
  {
    slug: "canned-corn",
    name: "Кукуруза консервированная",
    category: "canned",
    brand: "уточнить",
    state: "canned_drained",
    measurement_basis: "per_100g_drained",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "Без жидкости из банки.",
  },
  {
    slug: "crispbread",
    name: "Хлебцы",
    category: "bakery",
    brand: "уточнить",
    state: "ready",
    measurement_basis: "per_100g_pack",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: true,
    requires_cooking: false,
    weighing_note: "По этикетке упаковки.",
  },
  {
    slug: "lavash",
    name: "Лаваш",
    category: "bakery",
    brand: "уточнить",
    state: "ready",
    measurement_basis: "per_100g_pack",
    kcal: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    source_name: "Этикетка упаковки",
    is_verified: false,
    allowed_for_snack: false,
    requires_cooking: false,
    weighing_note: "По этикетке упаковки.",
  },
];

export type SeedRecipe = {
  slug: string;
  name: string;
  meal_type: "main" | "snack";
  requires_cooking: boolean;
  prep_time_min: number;
  steps: string[];
  weighing_note: string;
  ingredients: Array<{ product_slug: string; min_g: number; max_g: number; default_g: number }>;
};

export const SEED_RECIPES: SeedRecipe[] = [
  {
    slug: "oats-milk-banana",
    name: "Овсянка с молоком и бананом",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 10,
    weighing_note: "Крупа — сухая, молоко — по этикетке.",
    steps: ["Сварить овсянку на воде без масла.", "Добавить молоко.", "Добавить нарезанный банан."],
    ingredients: [
      { product_slug: "oats-dry", min_g: 40, max_g: 80, default_g: 50 },
      { product_slug: "banana", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "omelette-tomato-pepper-cheese",
    name: "Омлет с помидорами, перцем и сыром",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 12,
    weighing_note: "Яйца и овощи — до готовки.",
    steps: [
      "Взбить яйца.",
      "Обжарить на антипригарной сковороде без масла с овощами.",
      "Добавить сыр.",
    ],
    ingredients: [
      { product_slug: "egg-whole", min_g: 100, max_g: 200, default_g: 150 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "bell-pepper", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "chicken-buckwheat-salad",
    name: "Курица с гречкой и овощным салатом",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 35,
    weighing_note: "Крупа и мясо — до варки.",
    steps: [
      "Отварить гречку на воде.",
      "Отварить или запечь курицу без масла.",
      "Смешать с овощами.",
    ],
    ingredients: [
      { product_slug: "chicken-breast-raw", min_g: 120, max_g: 220, default_g: 160 },
      { product_slug: "buckwheat-dry", min_g: 50, max_g: 90, default_g: 60 },
      { product_slug: "cucumber", min_g: 80, max_g: 200, default_g: 120 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "chicken-rice-zucchini",
    name: "Курица с рисом, кабачком и перцем",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 35,
    weighing_note: "Рис и мясо — до варки.",
    steps: ["Отварить рис.", "Приготовить курицу с овощами на воде."],
    ingredients: [
      { product_slug: "chicken-breast-raw", min_g: 120, max_g: 220, default_g: 160 },
      { product_slug: "rice-white-dry", min_g: 50, max_g: 90, default_g: 65 },
      { product_slug: "zucchini", min_g: 100, max_g: 200, default_g: 150 },
      { product_slug: "bell-pepper", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "beef-buckwheat-veg",
    name: "Говядина с гречкой, морковью и капустой",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 45,
    weighing_note: "Сырое мясо и сухая крупа.",
    steps: ["Отварить гречку.", "Тушить говядину с овощами на воде."],
    ingredients: [
      { product_slug: "beef-lean-raw", min_g: 120, max_g: 200, default_g: 150 },
      { product_slug: "buckwheat-dry", min_g: 50, max_g: 90, default_g: 60 },
      { product_slug: "carrot", min_g: 60, max_g: 120, default_g: 80 },
      { product_slug: "white-cabbage", min_g: 80, max_g: 180, default_g: 120 },
    ],
  },
  {
    slug: "pollock-rice-zucchini",
    name: "Минтай с рисом и кабачком",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 30,
    weighing_note: "Рыба и рис — до готовки.",
    steps: ["Отварить рис.", "Запечь или отварить минтай с кабачком."],
    ingredients: [
      { product_slug: "pollock-raw", min_g: 150, max_g: 250, default_g: 180 },
      { product_slug: "rice-white-dry", min_g: 50, max_g: 90, default_g: 65 },
      { product_slug: "zucchini", min_g: 100, max_g: 200, default_g: 150 },
    ],
  },
  {
    slug: "egg-chicken-buckwheat",
    name: "Гречка с яйцом, курицей и овощами",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 30,
    weighing_note: "Сухая крупа, сырое мясо.",
    steps: ["Сварить гречку.", "Приготовить курицу и яйцо.", "Добавить овощи."],
    ingredients: [
      { product_slug: "buckwheat-dry", min_g: 50, max_g: 90, default_g: 60 },
      { product_slug: "chicken-breast-raw", min_g: 100, max_g: 180, default_g: 140 },
      { product_slug: "egg-whole", min_g: 50, max_g: 150, default_g: 100 },
      { product_slug: "cucumber", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "apple-almond-snack",
    name: "Яблоко и миндаль",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "apple", min_g: 120, max_g: 200, default_g: 150 },
      { product_slug: "almond", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "banana-pumpkin-seeds-snack",
    name: "Банан и семечки тыквы",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "banana", min_g: 100, max_g: 150, default_g: 120 },
      { product_slug: "pumpkin-seeds", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "cherry-walnut-snack",
    name: "Вишня и грецкий орех",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "cherry", min_g: 100, max_g: 180, default_g: 120 },
      { product_slug: "walnut", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "banana-walnut-snack",
    name: "Банан и грецкий орех",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "banana", min_g: 100, max_g: 150, default_g: 120 },
      { product_slug: "walnut", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "apple-almond-alt",
    name: "Яблоко и грецкий орех",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "apple", min_g: 120, max_g: 200, default_g: 150 },
      { product_slug: "walnut", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  // --- 20 основных (только verified-ингредиенты для автогенерации) ---
  {
    slug: "oats-banana-apple",
    name: "Овсянка с бананом и яблоком",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 10,
    weighing_note: "Крупа — сухая.",
    steps: ["Сварить овсянку на воде без масла.", "Добавить нарезанные фрукты."],
    ingredients: [
      { product_slug: "oats-dry", min_g: 40, max_g: 80, default_g: 50 },
      { product_slug: "banana", min_g: 60, max_g: 120, default_g: 80 },
      { product_slug: "apple", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "oats-pancake-egg-banana",
    name: "Овсяный блин с яйцом и бананом",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 15,
    weighing_note: "Овсянка — сухая, яйцо — в граммах.",
    steps: ["Смешать овсянку, яйцо и банан.", "Выпечь на антипригарной сковороде без масла."],
    ingredients: [
      { product_slug: "oats-dry", min_g: 40, max_g: 70, default_g: 50 },
      { product_slug: "egg-whole", min_g: 50, max_g: 100, default_g: 50 },
      { product_slug: "banana", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "omelette-tomato-pepper",
    name: "Омлет с помидорами и перцем",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 12,
    weighing_note: "Яйца и овощи — до готовки.",
    steps: ["Взбить яйца.", "Готовить с овощами на антипригарной сковороде без масла."],
    ingredients: [
      { product_slug: "egg-whole", min_g: 100, max_g: 200, default_g: 150 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "bell-pepper", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "omelette-napa-tomato",
    name: "Омлет с пекинской капустой и помидорами",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 12,
    weighing_note: "Яйца и овощи — до готовки.",
    steps: ["Взбить яйца.", "Добавить нашинкованную капусту и помидоры.", "Готовить без масла."],
    ingredients: [
      { product_slug: "egg-whole", min_g: 100, max_g: 200, default_g: 150 },
      { product_slug: "napa-cabbage", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "chicken-eggplant-tomato",
    name: "Курица с баклажанами и помидорами",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 35,
    weighing_note: "Мясо — сырое, до готовки.",
    steps: ["Тушить курицу с овощами на воде без масла."],
    ingredients: [
      { product_slug: "chicken-breast-raw", min_g: 120, max_g: 220, default_g: 160 },
      { product_slug: "eggplant", min_g: 100, max_g: 200, default_g: 150 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "beef-rice-vegetables",
    name: "Говядина с рисом и овощами",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 40,
    weighing_note: "Рис — сухой, мясо — сырое.",
    steps: ["Отварить рис.", "Тушить говядину с овощами на воде."],
    ingredients: [
      { product_slug: "beef-lean-raw", min_g: 120, max_g: 200, default_g: 150 },
      { product_slug: "rice-white-dry", min_g: 50, max_g: 90, default_g: 65 },
      { product_slug: "carrot", min_g: 60, max_g: 120, default_g: 80 },
      { product_slug: "bell-pepper", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "beef-eggplant-tomato",
    name: "Говядина с баклажанами и помидорами",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 40,
    weighing_note: "Мясо — сырое.",
    steps: ["Тушить говядину с овощами на воде."],
    ingredients: [
      { product_slug: "beef-lean-raw", min_g: 120, max_g: 200, default_g: 150 },
      { product_slug: "eggplant", min_g: 100, max_g: 200, default_g: 150 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "pollock-buckwheat-cabbage",
    name: "Минтай с гречкой и капустой",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 30,
    weighing_note: "Крупа и рыба — до готовки.",
    steps: ["Отварить гречку.", "Приготовить минтай с капустой."],
    ingredients: [
      { product_slug: "pollock-raw", min_g: 150, max_g: 250, default_g: 180 },
      { product_slug: "buckwheat-dry", min_g: 50, max_g: 90, default_g: 60 },
      { product_slug: "white-cabbage", min_g: 80, max_g: 180, default_g: 120 },
    ],
  },
  {
    slug: "pollock-veg-rice",
    name: "Минтай с овощами и рисом",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 30,
    weighing_note: "Рис — сухой, рыба — сырая.",
    steps: ["Отварить рис.", "Запечь минтай с овощами."],
    ingredients: [
      { product_slug: "pollock-raw", min_g: 150, max_g: 250, default_g: 180 },
      { product_slug: "rice-white-dry", min_g: 50, max_g: 90, default_g: 65 },
      { product_slug: "zucchini", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "carrot", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "rice-chicken-vegetables",
    name: "Рис с курицей и овощами",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 35,
    weighing_note: "Рис — сухой.",
    steps: ["Отварить рис.", "Приготовить курицу с овощами."],
    ingredients: [
      { product_slug: "rice-white-dry", min_g: 50, max_g: 90, default_g: 65 },
      { product_slug: "chicken-breast-raw", min_g: 120, max_g: 220, default_g: 160 },
      { product_slug: "bell-pepper", min_g: 60, max_g: 120, default_g: 80 },
      { product_slug: "carrot", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "baked-oats-apple-egg",
    name: "Запечённая овсянка с яблоком и яйцом",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 25,
    weighing_note: "Овсянка — сухая.",
    steps: ["Смешать овсянку, яйцо и яблоко.", "Запечь без масла."],
    ingredients: [
      { product_slug: "oats-dry", min_g: 40, max_g: 80, default_g: 55 },
      { product_slug: "apple", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "egg-whole", min_g: 50, max_g: 100, default_g: 50 },
    ],
  },
  {
    slug: "chicken-buckwheat-carrot",
    name: "Курица с гречкой и морковью",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 35,
    weighing_note: "Крупа и мясо — до варки.",
    steps: ["Отварить гречку.", "Приготовить курицу с морковью."],
    ingredients: [
      { product_slug: "chicken-breast-raw", min_g: 120, max_g: 220, default_g: 160 },
      { product_slug: "buckwheat-dry", min_g: 50, max_g: 90, default_g: 60 },
      { product_slug: "carrot", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "beef-rice-zucchini-pepper",
    name: "Говядина с рисом, кабачком и перцем",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 40,
    weighing_note: "Рис — сухой.",
    steps: ["Отварить рис.", "Тушить говядину с овощами."],
    ingredients: [
      { product_slug: "beef-lean-raw", min_g: 120, max_g: 200, default_g: 150 },
      { product_slug: "rice-white-dry", min_g: 50, max_g: 90, default_g: 65 },
      { product_slug: "zucchini", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "bell-pepper", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "pollock-cucumber-tomato",
    name: "Минтай с гречкой, огурцом и помидором",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 30,
    weighing_note: "Рыба — сырая.",
    steps: ["Отварить гречку.", "Приготовить минтай.", "Добавить свежие овощи."],
    ingredients: [
      { product_slug: "pollock-raw", min_g: 150, max_g: 250, default_g: 180 },
      { product_slug: "buckwheat-dry", min_g: 50, max_g: 90, default_g: 60 },
      { product_slug: "cucumber", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "oats-cherry-apple",
    name: "Овсянка с вишней и яблоком",
    meal_type: "main",
    requires_cooking: true,
    prep_time_min: 10,
    weighing_note: "Крупа — сухая.",
    steps: ["Сварить овсянку на воде.", "Добавить фрукты."],
    ingredients: [
      { product_slug: "oats-dry", min_g: 40, max_g: 80, default_g: 50 },
      { product_slug: "cherry", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "apple", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  // --- 12 перекусов без готовки ---
  {
    slug: "banana-almond-snack",
    name: "Банан и миндаль",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "banana", min_g: 100, max_g: 150, default_g: 120 },
      { product_slug: "almond", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "apple-cherry-snack",
    name: "Яблоко и вишня",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "apple", min_g: 100, max_g: 180, default_g: 130 },
      { product_slug: "cherry", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "avocado-walnut-snack",
    name: "Авокадо и грецкий орех",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 2,
    weighing_note: "Мякоть авокадо без косточки.",
    steps: ["Нарезать авокадо, добавить орехи.", "Съесть."],
    ingredients: [
      { product_slug: "avocado", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "walnut", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "carrot-apple-snack",
    name: "Морковь и яблоко",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 2,
    weighing_note: "Сырые, съедобная часть.",
    steps: ["Нарезать и съесть."],
    ingredients: [
      { product_slug: "carrot", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "apple", min_g: 100, max_g: 180, default_g: 130 },
    ],
  },
  {
    slug: "cherry-almond-snack",
    name: "Вишня и миндаль",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "cherry", min_g: 100, max_g: 180, default_g: 120 },
      { product_slug: "almond", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "cucumber-apple-snack",
    name: "Огурец и яблоко",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Сырые.",
    steps: ["Нарезать и съесть."],
    ingredients: [
      { product_slug: "cucumber", min_g: 100, max_g: 200, default_g: 150 },
      { product_slug: "apple", min_g: 80, max_g: 150, default_g: 100 },
    ],
  },
  {
    slug: "banana-almond-pumpkin-snack",
    name: "Банан, миндаль и семечки",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Готовые продукты.",
    steps: ["Съесть вместе."],
    ingredients: [
      { product_slug: "banana", min_g: 80, max_g: 130, default_g: 100 },
      { product_slug: "almond", min_g: 8, max_g: 20, default_g: 12 },
      { product_slug: "pumpkin-seeds", min_g: 8, max_g: 20, default_g: 12 },
    ],
  },
  // --- белковые перекусы без приготовления (1+3, после верификации упаковок) ---
  {
    slug: "tuna-cucumber-crispbread",
    name: "Тунец, огурец и хлебцы",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 3,
    weighing_note: "Тунец — без жидкости, хлебцы — по этикетке.",
    steps: ["Открыть тунец, смешать с нарезанным огурцом.", "Выложить на хлебцы."],
    ingredients: [
      { product_slug: "canned-tuna", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "cucumber", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "crispbread", min_g: 20, max_g: 40, default_g: 30 },
    ],
  },
  {
    slug: "tuna-tomato-crispbread",
    name: "Тунец, помидор и хлебцы",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 3,
    weighing_note: "Тунец — без жидкости.",
    steps: ["Смешать тунец с помидором.", "Подать с хлебцами."],
    ingredients: [
      { product_slug: "canned-tuna", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "crispbread", min_g: 20, max_g: 40, default_g: 30 },
    ],
  },
  {
    slug: "tuna-napa-lavash",
    name: "Тунец, пекинская капуста и лаваш",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 3,
    weighing_note: "Тунец — без жидкости, лаваш — по этикетке.",
    steps: ["Смешать тунец с нашинкованной капустой.", "Завернуть в лаваш."],
    ingredients: [
      { product_slug: "canned-tuna", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "napa-cabbage", min_g: 60, max_g: 120, default_g: 80 },
      { product_slug: "lavash", min_g: 40, max_g: 80, default_g: 50 },
    ],
  },
  {
    slug: "tuna-avocado-crispbread",
    name: "Тунец, авокадо и хлебцы",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 3,
    weighing_note: "Тунец — без жидкости.",
    steps: ["Размять авокадо, смешать с тунцом.", "Подать с хлебцами."],
    ingredients: [
      { product_slug: "canned-tuna", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "avocado", min_g: 60, max_g: 120, default_g: 80 },
      { product_slug: "crispbread", min_g: 20, max_g: 40, default_g: 30 },
    ],
  },
  {
    slug: "tuna-corn-pepper",
    name: "Тунец, кукуруза и перец",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 3,
    weighing_note: "Консервы — без жидкости.",
    steps: ["Смешать тунец, кукурузу и нарезанный перец."],
    ingredients: [
      { product_slug: "canned-tuna", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "canned-corn", min_g: 60, max_g: 120, default_g: 80 },
      { product_slug: "bell-pepper", min_g: 60, max_g: 120, default_g: 80 },
    ],
  },
  {
    slug: "cheese-tomato-crispbread",
    name: "Сыр, помидор и хлебцы",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 2,
    weighing_note: "Сыр и хлебцы — по этикетке.",
    steps: ["Нарезать сыр и помидор.", "Подать с хлебцами."],
    ingredients: [
      { product_slug: "hard-cheese", min_g: 30, max_g: 60, default_g: 40 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "crispbread", min_g: 20, max_g: 40, default_g: 30 },
    ],
  },
  {
    slug: "cheese-cucumber-crispbread",
    name: "Сыр, огурец и хлебцы",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 2,
    weighing_note: "Сыр и хлебцы — по этикетке.",
    steps: ["Нарезать сыр и огурец.", "Подать с хлебцами."],
    ingredients: [
      { product_slug: "hard-cheese", min_g: 30, max_g: 60, default_g: 40 },
      { product_slug: "cucumber", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "crispbread", min_g: 20, max_g: 40, default_g: 30 },
    ],
  },
  {
    slug: "milk-apple-almond",
    name: "Молоко, яблоко и миндаль",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Молоко — по этикетке.",
    steps: ["Выпить молоко, съесть яблоко с миндалём."],
    ingredients: [
      { product_slug: "lactose-free-milk", min_g: 150, max_g: 250, default_g: 200 },
      { product_slug: "apple", min_g: 100, max_g: 180, default_g: 130 },
      { product_slug: "almond", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "milk-banana-pumpkin",
    name: "Молоко, банан и семечки тыквы",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Молоко — по этикетке.",
    steps: ["Выпить молоко, съесть банан с семечками."],
    ingredients: [
      { product_slug: "lactose-free-milk", min_g: 150, max_g: 250, default_g: 200 },
      { product_slug: "banana", min_g: 80, max_g: 130, default_g: 100 },
      { product_slug: "pumpkin-seeds", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "avocado-tomato-crispbread",
    name: "Авокадо, помидор и хлебцы",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 2,
    weighing_note: "Хлебцы — по этикетке.",
    steps: ["Намазать хлебцы авокадо, добавить помидор."],
    ingredients: [
      { product_slug: "avocado", min_g: 60, max_g: 120, default_g: 80 },
      { product_slug: "tomato", min_g: 80, max_g: 150, default_g: 100 },
      { product_slug: "crispbread", min_g: 20, max_g: 40, default_g: 30 },
    ],
  },
  {
    slug: "apple-cheese-almond",
    name: "Яблоко, сыр и миндаль",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 2,
    weighing_note: "Сыр — по этикетке.",
    steps: ["Нарезать яблоко и сыр, добавить миндаль."],
    ingredients: [
      { product_slug: "apple", min_g: 100, max_g: 180, default_g: 130 },
      { product_slug: "hard-cheese", min_g: 25, max_g: 50, default_g: 35 },
      { product_slug: "almond", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
  {
    slug: "cherry-milk-walnut",
    name: "Вишня, молоко и грецкий орех",
    meal_type: "snack",
    requires_cooking: false,
    prep_time_min: 1,
    weighing_note: "Молоко — по этикетке.",
    steps: ["Выпить молоко, съесть вишню с орехами."],
    ingredients: [
      { product_slug: "cherry", min_g: 100, max_g: 180, default_g: 120 },
      { product_slug: "lactose-free-milk", min_g: 150, max_g: 250, default_g: 200 },
      { product_slug: "walnut", min_g: 10, max_g: 25, default_g: 15 },
    ],
  },
];

/** Slug'и продуктов белого списка для валидации. */
export const ALLOWED_PRODUCT_SLUGS = new Set(SEED_PRODUCTS.map((p) => p.slug));
